baseURL = 'https://nhtmai.github.io/blog/'
languageCode = 'en-us'
title = 'bloodwork'
theme = 'archie'

[params]
    mode="auto" # color-mode → light,dark,toggle or auto
	customcss = ["css/main.css"]

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
